import os
import math
import re

from PySide6.QtWidgets import QApplication, QDialog, QFrame, QGraphicsOpacityEffect, QGridLayout, QHBoxLayout, QInputDialog, QLabel, QListWidget, QListWidgetItem, QProgressBar, QPushButton, QScrollArea, QScrollBar, QSizePolicy, QVBoxLayout, QWidget
from PySide6.QtCore import Qt, QEvent, QObject, QPoint, QSize, QTimer, Signal
from PySide6.QtGui import QFontMetrics, QIcon, QShortcut, QKeySequence
from i18n import t
import nerdfont as nf

from palworld_aio import constants
from resource_resolver import resource_path
from palworld_aio.utils import extract_value, safe_nested_get, calculate_max_hp, calculate_shot_attack
from palworld_aio.ui.chrome.styles import slot_full, slot_selected, TOOLTIP_STYLE
from palworld_aio.ui.chrome.sidebar_widget import NerdBtn
from palworld_aio.ui.dialogs.skill_picker import SkillPicker
from . import data as _data
from . import icons as _icons
from .icons import _get_awake_pixmap
from .widgets import _CircularIcon, _ShinyStar, CornerBracketWidget, GlowRing, PassiveEffectOverlay, PortraitBracketWidget, RotatingCircleWidget
from .legacy_frame import PalFrame
from .pal_info_display import PalInfoDisplayMixin
from .pal_info_handlers import PalInfoHandlerMixin

class PalInfoWidget(PalInfoDisplayMixin, PalInfoHandlerMixin, QFrame):
    pal_data_changed = Signal()
    _ELEMENT_MAP = {'Normal': ('⚪', '#9CA3AF'), 'Fire': ('🔥', '#EF4444'), 'Water': ('💧', '#3B82F6'), 'Leaf': ('🌿', '#4ADE80'), 'Grass': ('🌿', '#4ADE80'), 'Electricity': ('⚡', '#FBBF24'), 'Electric': ('⚡', '#FBBF24'), 'Ice': ('❄️', '#67E8F9'), 'Earth': ('🪨', '#A78BFA'), 'Ground': ('🪨', '#A78BFA'), 'Dark': ('🌑', '#6B21A8'), 'Dragon': ('🐉', '#818CF8'), 'None': ('○', '#6B7280')}
    _ELEMENT_COLORS = {'Normal': '#9CA3AF', 'Fire': '#EF4444', 'Water': '#3B82F6', 'Leaf': '#4ADE80', 'Grass': '#4ADE80', 'Electricity': '#FBBF24', 'Electric': '#FBBF24', 'Ice': '#67E8F9', 'Earth': '#A78BFA', 'Ground': '#A78BFA', 'Dark': '#6B21A8', 'Dragon': '#818CF8', 'None': '#6B7280'}
    NATIVE_WORK_ORDER = ('EmitFlame', 'Watering', 'Seeding', 'GenerateElectricity', 'Handcraft', 'Collection', 'Deforest', 'Mining', 'ProductMedicine', 'Cool', 'Transport', 'MonsterFarm')
    _WORK_SUITABILITY_DISPLAY = {'EmitFlame': 'Kindling', 'Watering': 'Watering', 'Seeding': 'Seeding', 'GenerateElectricity': 'Electricity', 'Handcraft': 'Handiwork', 'Collection': 'Harvesting', 'Deforest': 'Lumbering', 'Mining': 'Mining', 'ProductMedicine': 'Medicine', 'Cool': 'Cooling', 'Transport': 'Transport', 'MonsterFarm': 'Farming'}
    _WORK_SUITABILITY_ICON_KEYS = ['palwork_00', 'palwork_01', 'palwork_02', 'palwork_03', 'palwork_04', 'palwork_05', 'palwork_06', 'palwork_07', 'palwork_08', 'palwork_10', 'palwork_11', 'palwork_12']
    def __init__(self, parent=None):
        super().__init__(parent)
        self.current_pal = None
        self.last_clicked_data = None
        self._hovered_data = None
        self.setObjectName('palInfoPanel')
        self._raw = None
        self._build()
        self.installEventFilter(self)
    def set_hover_pal(self, pal_data):
        self._as_page = 0
        self._ps_page = 0
        self._hovered_data = pal_data
        if pal_data is None:
            self._update_stack_state()
            self._clear_display()
            return
        self._update_stack_state()
        self._update_display(pal_data)
    def set_clicked_pal(self, pal_data):
        self._as_page = 0
        self._ps_page = 0
        self.last_clicked_data = pal_data
        if pal_data is None:
            self._update_stack_state()
            self._clear_display()
            return
        self._update_stack_state()
        self._update_display(pal_data)
    def clear_hover(self):
        self._hovered_data = None
        if self.last_clicked_data is not None:
            self._update_display(self.last_clicked_data)
            return
        self._update_stack_state()
        self._clear_display()
    def _update_stack_state(self):
        if self._hovered_data is None and self.last_clicked_data is None:
            self._no_data_overlay.show()
            self._data_scroll.hide()
        else:
            self._no_data_overlay.hide()
            self._data_scroll.show()
    def _clear_display(self):
        self.name_lbl.setText('--')
        self.level_num_lbl.setText('--')
        self.next_lbl.setText('0')
        self.exp_header_bar.setValue(0)
        self.trust_bar.setValue(0)
        self.trust_bar.setFormat('-- / --')
        self.hp_bar.setValue(0)
        self.hp_bar.setFormat('--')
        self.hunger_bar.setValue(0)
        self.hunger_bar.setFormat('-- / --')
        self.san_bar.setValue(0)
        self.san_bar.setFormat('-- / --')
        self.atk_lbl.setText('--')
        self.def_lbl.setText('--')
        self.wspd_lbl.setText('--')
        for icon_lbl, (val_lbl, _, val_badge) in zip(self.work_icon_labels, self.work_icon_values):
            icon_lbl.setStyleSheet('background: transparent; border: none;')
            eff = icon_lbl.graphicsEffect()
            if isinstance(eff, QGraphicsOpacityEffect):
                eff.setOpacity(0.06)
            val_lbl.setText('')
            val_lbl.setStyleSheet('font-size: 9px; font-weight: 700; color: transparent; background: transparent; border: none;')
            val_badge.setStyleSheet('background: transparent; border: none;')
        gender_def = _icons._get_ui_icon_pixmap('gender_female', 18)
        if gender_def:
            self.gender_icon.setIcon(QIcon(gender_def))
        self.gender_icon.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 4px; } QPushButton:hover { background: rgba(255,255,255,0.08); }')
        while self.type_icons_layout.count():
            item = self.type_icons_layout.takeAt(0)
            if item and item.widget():
                item.widget().deleteLater()
        for fc in self.food_icon_labels:
            fc.setStyleSheet('background: transparent; border: none;')
            foff = _icons._get_ui_icon_pixmap('food_off', 12)
            if foff:
                fc.setPixmap(foff)
            eff = fc.graphicsEffect()
            if isinstance(eff, QGraphicsOpacityEffect):
                eff.setOpacity(0.14)
        self.partner_name_lbl.setText('--')
        self.partner_lvl_lbl.setText('Lv --')
        self.partner_desc_lbl.setText(t('pal_editor.no_pal_data') if t else 'No Pal Data')
        while self.active_skills_list.count():
            item = self.active_skills_list.takeAt(0)
            if item and item.widget():
                item.widget().deleteLater()
        for s in self.passive_slots:
            s.setText('--')
            s.setStyleSheet('font-size: 9px; font-weight: 700; color: rgba(255,255,255,0.3); background: transparent; border: none;')
            parent_frame = s.parentWidget()
            if parent_frame and parent_frame.objectName() == 'passiveCard':
                parent_frame.setStyleSheet('QFrame#passiveCard { background: rgba(255,255,255,0.03); border: none; border-radius: 4px; }')
        for i in range(len(self.passive_cards)):
            self._set_passive_overlay(i, None)
        self.stat_plus_lbl.setText('--')
        self.soul_buildup_icon.clear()
        self.iv_icon.clear()
        self.soul_row_icon.clear()
        self._stop_star_shine()
        for sl in self.star_labels:
            sl.set_filled(False)
            sl.stop_shine()
        self.portrait_icon.clear()
        self.dna_overlay.hide()
        self.lock_overlay.hide()
        self.boss_overlay.hide()
        self.lucky_overlay.hide()
        self.awake_overlay.hide()
        self.portrait_ring.set_awakened(False)
        self._update_stack_state()
        if hasattr(self, '_stat_tip'):
            self._stat_tip.hide()
    def _set_passive_overlay(self, index, mode):
        if index >= len(self.passive_cards) or index >= len(self.passive_overlays):
            return
        card = self.passive_cards[index]
        overlay = self.passive_overlays[index]
        overlay.setGeometry(0, 0, card.width(), card.height())
        overlay.set_mode(mode)
    def _build(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        scroll = QScrollArea()
        self._data_scroll = scroll
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll.setStyleSheet('QScrollArea { background: transparent; border: none; }')
        inner = QWidget()
        inner.setObjectName('palInfoInner')
        inner.setStyleSheet('QWidget#palInfoInner { background: rgba(8,10,16,0.98); border: 1px solid rgba(30,40,55,0.9); border-radius: 6px; }')
        inner_layout = QVBoxLayout(inner)
        inner_layout.setContentsMargins(4, 2, 4, 2)
        inner_layout.setSpacing(0)
        self._build_header(inner_layout)
        self._build_body(inner_layout)
        self._build_skills(inner_layout)
        scroll.setWidget(inner)
        layout.addWidget(scroll)
        self._no_data_overlay = QLabel(t('pal_editor.no_pal_data') if t else 'No Pal Data', self)
        self._no_data_overlay.setAlignment(Qt.AlignCenter)
        self._no_data_overlay.setStyleSheet('font-size: 16px; font-weight: 700; color: rgba(255,255,255,0.18); background: rgba(8,10,16,0.98); border: 1px solid rgba(30,40,55,0.9); border-radius: 6px;')
        self._no_data_overlay.show()
        scroll.hide()
        self._c_shortcut = QShortcut(QKeySequence(Qt.Key_C), self)
        self._c_shortcut.activated.connect(lambda: self.last_clicked_data is not None and self._toggle_skills_view())
        self._showing_active_skills = True
        self._l_shortcut = QShortcut(QKeySequence(Qt.Key_L), self)
        self._l_shortcut.activated.connect(lambda: self.last_clicked_data is not None and self._on_passive_loadout())
        self._stat_tip = QLabel(None, Qt.Tool | Qt.FramelessWindowHint)
        self._stat_tip.setVisible(False)
        self._stat_tip.setWordWrap(False)
        self._stat_tip.setStyleSheet('background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px;')
        self._stat_tip.setAttribute(Qt.WA_ShowWithoutActivating)
        self._stat_tip.setAttribute(Qt.WA_TransparentForMouseEvents)
    def resizeEvent(self, event):
        super().resizeEvent(event)
        if hasattr(self, '_no_data_overlay'):
            self._no_data_overlay.setGeometry(self.rect())
    def _toggle_skills_view(self):
        self._showing_active_skills = not self._showing_active_skills
        self.active_skills_frame.setVisible(self._showing_active_skills)
        self.partner_frame.setVisible(not self._showing_active_skills)
    def _build_header(self, parent):
        header = QWidget()
        header.setStyleSheet('background: transparent; border: none;')
        hrow = QHBoxLayout()
        hrow.setContentsMargins(0, 0, 0, 0)
        hrow.setSpacing(2)
        hrow.setAlignment(Qt.AlignLeft)
        level_box = CornerBracketWidget('#7DD3FC')
        lv_layout = QVBoxLayout(level_box)
        lv_layout.setContentsMargins(2, 2, 2, 2)
        lv_layout.setSpacing(0)
        lv_label = QLabel(t('pal_editor.level') if t else 'LEVEL')
        self._lv_label = lv_label
        lv_label.setAlignment(Qt.AlignCenter)
        lv_label.setStyleSheet('font-size: 7px; font-weight: 600; color: #7DD3FC; letter-spacing: 2px; background: transparent; border: none;')
        lv_layout.addWidget(lv_label)
        self.level_num_lbl = QLabel('80')
        self.level_num_lbl.setAlignment(Qt.AlignCenter)
        self.level_num_lbl.setStyleSheet('font-size: 20px; font-weight: 800; color: #FFFFFF; background: transparent; border: none;')
        self.level_num_lbl.setCursor(Qt.PointingHandCursor)
        self.level_num_lbl.installEventFilter(self)
        lv_layout.addWidget(self.level_num_lbl)
        hrow.addWidget(level_box, 0, Qt.AlignTop)
        name_col = QWidget()
        name_col.setStyleSheet('background: transparent; border: none;')
        name_col.setMinimumWidth(180)
        name_col.setMaximumWidth(350)
        nc_layout = QVBoxLayout(name_col)
        nc_layout.setContentsMargins(0, 0, 0, 0)
        nc_layout.setSpacing(0)
        name_row = QHBoxLayout()
        name_row.setContentsMargins(0, 0, 0, 0)
        name_row.setSpacing(4)
        self.name_lbl = QLabel('Gobfinned')
        self.name_lbl.setStyleSheet('font-size: 14px; font-weight: 700; color: #FFFFFF; background: transparent; border: none;')
        self.name_lbl.setCursor(Qt.PointingHandCursor)
        self.name_lbl.setWordWrap(True)
        self.name_lbl.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        self.name_lbl.installEventFilter(self)
        name_row.addWidget(self.name_lbl, 1)
        self.type_icons_container = QWidget()
        self.type_icons_container.setStyleSheet('background: transparent; border: none;')
        self.type_icons_layout = QHBoxLayout(self.type_icons_container)
        self.type_icons_layout.setContentsMargins(0, 0, 0, 0)
        self.type_icons_layout.setSpacing(2)
        self.type_icons_layout.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        name_row.addWidget(self.type_icons_container)
        nc_layout.addLayout(name_row)
        nc_layout.addStretch()
        next_row = QHBoxLayout()
        next_row.setContentsMargins(0, 0, 0, 0)
        next_row.setSpacing(3)
        next_label = QLabel('NEXT')
        next_label.setStyleSheet('font-size: 9px; font-weight: 600; color: #9CA3AF; background: transparent; border: none;')
        next_row.addWidget(next_label)
        self.next_lbl = QLabel('0')
        self.next_lbl.setStyleSheet('font-size: 9px; font-weight: 600; color: #E2E8F0; background: transparent; border: none;')
        next_row.addWidget(self.next_lbl)
        next_row.addStretch()
        self.gender_icon = QPushButton()
        self.gender_icon.setFixedSize(18, 18)
        self.gender_icon.setIconSize(QSize(14, 14))
        gender_def = _icons._get_ui_icon_pixmap('gender_female', 14)
        if gender_def:
            self.gender_icon.setIcon(QIcon(gender_def))
        self.gender_icon.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; } QPushButton:hover { background: rgba(255,255,255,0.08); } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.gender_icon.setCursor(Qt.PointingHandCursor)
        self.gender_icon.clicked.connect(self._on_gender_click)
        next_row.addWidget(self.gender_icon)
        base_dir = constants.get_base_path()
        self.info_predator_btn = NerdBtn(nf.icons['nf-fa-paw'])
        self.info_predator_btn.setCheckable(True)
        self.info_predator_btn.setFixedSize(18, 18)
        self.info_predator_btn.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; } QPushButton:checked { background: rgba(239,68,68,0.2); border: 1px solid #EF4444; color: #EF4444; } QPushButton:hover { background: rgba(255,255,255,0.08); } QPushButton:disabled { background: transparent; border: 1px solid rgba(255,255,255,0.03); color: rgba(255,255,255,0.15); } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.info_predator_btn.setCursor(Qt.PointingHandCursor)
        self.info_predator_btn.clicked.connect(self._on_predator_toggle)
        next_row.addWidget(self.info_predator_btn)
        self.info_boss_btn = QPushButton()
        self.info_boss_btn.setIcon(QIcon(resource_path(base_dir, 'boss_alpha.webp')))
        self.info_boss_btn.setIconSize(QSize(14, 14))
        self.info_boss_btn.setCheckable(True)
        self.info_boss_btn.setFixedSize(18, 18)
        self.info_boss_btn.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; } QPushButton:checked { background: rgba(245,158,11,0.2); border: 1px solid #F59E0B; } QPushButton:hover { background: rgba(255,255,255,0.08); } QPushButton:disabled { background: transparent; border: 1px solid rgba(255,255,255,0.03); } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.info_boss_btn.setCursor(Qt.PointingHandCursor)
        self.info_boss_btn.clicked.connect(self._on_boss_toggle)
        next_row.addWidget(self.info_boss_btn)
        self.info_lucky_btn = QPushButton()
        self.info_lucky_btn.setIcon(QIcon(resource_path(base_dir, 'boss_shiny.webp')))
        self.info_lucky_btn.setIconSize(QSize(14, 14))
        self.info_lucky_btn.setCheckable(True)
        self.info_lucky_btn.setFixedSize(18, 18)
        self.info_lucky_btn.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; } QPushButton:checked { background: rgba(168,85,247,0.2); border: 1px solid #A855F7; } QPushButton:hover { background: rgba(255,255,255,0.08); } QPushButton:disabled { background: transparent; border: 1px solid rgba(255,255,255,0.03); } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.info_lucky_btn.setCursor(Qt.PointingHandCursor)
        self.info_lucky_btn.clicked.connect(self._on_lucky_toggle)
        next_row.addWidget(self.info_lucky_btn)
        self.info_awake_btn = QPushButton()
        self.info_awake_btn.setCheckable(True)
        self.info_awake_btn.setFixedSize(18, 18)
        self.info_awake_btn.setIconSize(QSize(14, 14))
        awake_icon = _get_awake_pixmap(14)
        if awake_icon:
            self.info_awake_btn.setIcon(QIcon(awake_icon))
        else:
            self.info_awake_btn.setText('🔥')
        self.info_awake_btn.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; font-size: 10px; } QPushButton:checked { background: rgba(251,191,36,0.2); border: 1px solid #FBBF24; } QPushButton:hover { background: rgba(255,255,255,0.08); } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.info_awake_btn.setCursor(Qt.PointingHandCursor)
        self.info_awake_btn.clicked.connect(self._on_awake_toggle)
        next_row.addWidget(self.info_awake_btn)
        self.info_cheat_btn = NerdBtn(nf.icons['nf-fa-bug'])
        self.info_cheat_btn.setCheckable(True)
        self.info_cheat_btn.setFixedSize(18, 18)
        self.info_cheat_btn.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; } QPushButton:checked { background: rgba(239,68,68,0.2); border: 1px solid #EF4444; color: #EF4444; } QPushButton:hover { background: rgba(255,255,255,0.08); } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.info_cheat_btn.setCursor(Qt.PointingHandCursor)
        self.info_cheat_btn.clicked.connect(self._on_cheat_toggle)
        next_row.addWidget(self.info_cheat_btn)
        self.info_max_btn = NerdBtn(nf.icons['nf-md-database_arrow_up'])
        self.info_max_btn.setFixedSize(18, 18)
        self.info_max_btn.setStyleSheet('QPushButton { font-size: 12px; padding: 0px; margin: 0px; background: transparent; color: #4ADE80; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; } QPushButton:hover { background: rgba(74,222,128,0.15); color: #FFFFFF; } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.info_max_btn.setCursor(Qt.PointingHandCursor)
        self.info_max_btn.clicked.connect(self._on_max_click)
        next_row.addWidget(self.info_max_btn)
        self.info_dna_btn = QPushButton()
        self.info_dna_btn.setCheckable(True)
        self.info_dna_btn.setFixedSize(18, 18)
        self.info_dna_btn.setIconSize(QSize(14, 14))
        dna_icon = _icons._get_ui_icon_pixmap('dna', 14)
        if dna_icon:
            self.info_dna_btn.setIcon(QIcon(dna_icon))
        self.info_dna_btn.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; } QPushButton:checked { background: rgba(34,211,238,0.2); border: 1px solid #22D3EE; } QPushButton:hover { background: rgba(255,255,255,0.08); } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.info_dna_btn.setCursor(Qt.PointingHandCursor)
        self.info_dna_btn.clicked.connect(self._on_dna_toggle)
        next_row.addWidget(self.info_dna_btn)
        self.info_fav_btn = QPushButton()
        self.info_fav_btn.setFixedSize(18, 18)
        self.info_fav_btn.setIconSize(QSize(14, 14))
        self.info_fav_btn.setStyleSheet('QPushButton { background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 3px; } QPushButton:hover { background: rgba(255,255,255,0.08); } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        self.info_fav_btn.setCursor(Qt.PointingHandCursor)
        self.info_fav_btn.clicked.connect(self._on_fav_toggle)
        next_row.addWidget(self.info_fav_btn)
        nc_layout.addLayout(next_row)
        hrow.addWidget(name_col, 0, Qt.AlignTop)
        header_layout = QVBoxLayout(header)
        header_layout.setContentsMargins(0, 0, 0, 0)
        header_layout.setSpacing(1)
        header_layout.addLayout(hrow)
        self.exp_header_bar = QProgressBar()
        self.exp_header_bar.setFixedHeight(3)
        self.exp_header_bar.setRange(0, 100)
        self.exp_header_bar.setValue(0)
        self.exp_header_bar.setTextVisible(False)
        self.exp_header_bar.setStyleSheet('QProgressBar { background: rgba(40,30,40,0.4); border: none; border-radius: 1px; } QProgressBar::chunk { background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #EC4899,stop:1 #F472B6); border-radius: 1px; }')
        header_layout.addWidget(self.exp_header_bar)
        parent.addWidget(header)
    def _on_bulk_sync_pal(self):
        if not self._raw:
            return
        owner = self.parent()
        while owner and (not hasattr(owner, 'party_pals')):
            owner = owner.parent()
        if not owner or not hasattr(owner, '_bulk_sync_pal'):
            return
        owner._bulk_sync_pal(self._raw)
    def _on_fav_set(self, idx):
        if not self._raw:
            return
        self._raw['FavoriteIndex'] = {'id': None, 'type': 'ByteProperty', 'value': {'type': 'None', 'value': idx}}
        self._refresh()
    def _build_body(self, parent):
        body = QWidget()
        body.setStyleSheet('background: transparent; border: none;')
        body_layout = QVBoxLayout(body)
        body_layout.setContentsMargins(0, 0, 0, 0)
        body_layout.setSpacing(2)
        columns = QHBoxLayout()
        columns.setContentsMargins(0, 0, 0, 0)
        columns.setSpacing(4)
        left_col = QWidget()
        left_col.setStyleSheet('background: transparent; border: none;')
        left_col.setFixedWidth(120)
        left_layout = QVBoxLayout(left_col)
        left_layout.setContentsMargins(0, 0, 0, 0)
        left_layout.setSpacing(2)
        self.star_container = QWidget()
        self.star_container.setCursor(Qt.PointingHandCursor)
        star_layout = QHBoxLayout(self.star_container)
        star_layout.setContentsMargins(0, 0, 0, 0)
        star_layout.setSpacing(1)
        star_layout.setAlignment(Qt.AlignCenter)
        self.star_labels = []
        for i in range(4):
            sl = _ShinyStar()
            sl._star_idx = i
            sl.installEventFilter(self)
            self.star_labels.append(sl)
            star_layout.addWidget(sl)
        self._star_shine_timer = QTimer(self)
        self._star_shine_timer.timeout.connect(self._tick_star_shine)
        self._star_shine_phase = 0.0
        left_layout.addWidget(self.star_container)
        portrait_frame = QFrame()
        self.portrait_frame = portrait_frame
        portrait_frame.setFixedSize(88, 88)
        portrait_frame.setObjectName('portraitGlow')
        portrait_frame.setStyleSheet('QFrame#portraitGlow { background: qradialgradient(cx:0.5,cy:0.5,radius:0.6,fx:0.5,fy:0.5,stop:0 rgba(125,211,252,0.12),stop:0.4 rgba(125,211,252,0.04),stop:1 transparent); border: none; border-radius: 44px; } QToolTip { background: rgba(18,20,24,0.98); color: #E2E8F0; border: 1px solid rgba(125,211,252,0.25); border-radius: 6px; padding: 6px 10px; font-size: 11px; }')
        pf_layout = QVBoxLayout(portrait_frame)
        pf_layout.setContentsMargins(2, 2, 2, 2)
        pf_layout.setAlignment(Qt.AlignCenter)
        self.bracket_wrapper = PortraitBracketWidget()
        self.bracket_wrapper.setFixedSize(80, 80)
        bw_layout = QVBoxLayout(self.bracket_wrapper)
        bw_layout.setContentsMargins(2, 2, 2, 2)
        bw_layout.setAlignment(Qt.AlignCenter)
        self.portrait_ring = GlowRing()
        self.portrait_ring.setFixedSize(72, 72)
        ring_layout = QVBoxLayout(self.portrait_ring)
        ring_layout.setContentsMargins(0, 0, 0, 0)
        self.portrait_icon = _CircularIcon(68)
        ring_layout.addWidget(self.portrait_icon, 0, Qt.AlignCenter)
        bw_layout.addWidget(self.portrait_ring, 0, Qt.AlignCenter)
        self.dna_overlay = QLabel(self.bracket_wrapper)
        self.dna_overlay.setFixedSize(14, 14)
        self.dna_overlay.setAlignment(Qt.AlignCenter)
        self.dna_overlay.setAttribute(Qt.WA_TranslucentBackground)
        dna_pix = _icons._get_ui_icon_pixmap('dna', 12)
        if dna_pix:
            self.dna_overlay.setPixmap(dna_pix)
        self.dna_overlay.setStyleSheet('background: transparent; border: none;')
        self.dna_overlay.move(4, 62)
        self.dna_overlay.hide()
        self.lock_overlay = QLabel(self.bracket_wrapper)
        self.lock_overlay.setFixedSize(14, 14)
        self.lock_overlay.setAlignment(Qt.AlignCenter)
        self.lock_overlay.setStyleSheet('font-size: 9px; color: rgba(255,255,255,0.65); background: rgba(0,0,0,0.55); border: 1px solid rgba(255,255,255,0.12); border-radius: 7px;')
        self.lock_overlay.setText('🔒')
        self.lock_overlay.move(62, 4)
        self.lock_overlay.hide()
        self.predator_overlay = QLabel(self.bracket_wrapper)
        self.predator_overlay.setFixedSize(14, 14)
        self.predator_overlay.setAlignment(Qt.AlignCenter)
        self.predator_overlay.setAttribute(Qt.WA_TranslucentBackground)
        self.predator_overlay.setStyleSheet('background: transparent; border: none; font-size: 10px; font-weight: bold; color: #EF4444;')
        self.predator_overlay.setText(nf.icons.get('nf-fa-paw', '🐾'))
        self.predator_overlay.move(50, 4)
        self.predator_overlay.hide()
        self.boss_overlay = QLabel(self.bracket_wrapper)
        self.boss_overlay.setFixedSize(14, 14)
        self.boss_overlay.setAlignment(Qt.AlignCenter)
        self.boss_overlay.setAttribute(Qt.WA_TranslucentBackground)
        self.boss_overlay.setStyleSheet('background: transparent; border: none;')
        self.boss_overlay.move(4, 4)
        self.boss_overlay.hide()
        self.lucky_overlay = QLabel(self.bracket_wrapper)
        self.lucky_overlay.setFixedSize(14, 14)
        self.lucky_overlay.setAlignment(Qt.AlignCenter)
        self.lucky_overlay.setAttribute(Qt.WA_TranslucentBackground)
        self.lucky_overlay.setStyleSheet('background: transparent; border: none;')
        self.lucky_overlay.move(4, 4)
        self.lucky_overlay.hide()
        self.awake_overlay = QLabel(self.bracket_wrapper)
        self.awake_overlay.setFixedSize(14, 14)
        self.awake_overlay.setAlignment(Qt.AlignCenter)
        self.awake_overlay.setAttribute(Qt.WA_TranslucentBackground)
        self.awake_overlay.setStyleSheet('background: transparent; border: none;')
        awake_overlay_pix = _get_awake_pixmap(12)
        if awake_overlay_pix:
            self.awake_overlay.setPixmap(awake_overlay_pix)
        else:
            self.awake_overlay.setStyleSheet('font-size: 10px; background: transparent; border: none;')
            self.awake_overlay.setText('🔥')
        self.awake_overlay.move(62, 62)
        self.awake_overlay.hide()
        self.rotating_circle = RotatingCircleWidget(self.bracket_wrapper)
        self.rotating_circle.setFixedSize(80, 80)
        self.rotating_circle.move(0, 0)
        self.rotating_circle.show()
        self.rotating_circle.lower()
        pf_layout.addWidget(self.bracket_wrapper, 0, Qt.AlignCenter)
        left_layout.addWidget(portrait_frame, 0, Qt.AlignCenter)
        soul_row = QHBoxLayout()
        soul_row.setContentsMargins(0, 0, 0, 0)
        soul_row.setSpacing(2)
        soul_row.setAlignment(Qt.AlignCenter)
        self.soul_buildup_icon = QLabel()
        self.soul_buildup_icon.setFixedSize(12, 12)
        self.soul_buildup_icon.setStyleSheet('background: transparent; border: none;')
        buildup_pix = _icons._get_ui_icon_pixmap('buildup', 12)
        if buildup_pix:
            self.soul_buildup_icon.setPixmap(buildup_pix)
        soul_row.addWidget(self.soul_buildup_icon)
        self.stat_plus_lbl = QLabel('+60')
        self.stat_plus_lbl.setAlignment(Qt.AlignCenter)
        self.stat_plus_lbl.setStyleSheet('font-size: 11px; font-weight: 700; color: #7DD3FC; background: transparent; border: none;')
        self.stat_plus_lbl.setAttribute(Qt.WA_TransparentForMouseEvents)
        soul_row.addWidget(self.stat_plus_lbl)
        left_layout.addLayout(soul_row, 1)
        ivs_row = QHBoxLayout()
        ivs_row.setSpacing(4)
        self.iv_icon = QLabel()
        self.iv_icon.setFixedSize(12, 12)
        self.iv_icon.setStyleSheet('background: transparent; border: none;')
        iv_pix = _icons._get_ui_icon_pixmap('talent_checker', 12)
        if iv_pix:
            self.iv_icon.setPixmap(iv_pix)
        ivs_row.addWidget(self.iv_icon)
        self.ivs_hp_lbl = QLabel('100')
        self.ivs_hp_lbl.setFixedWidth(24)
        self.ivs_hp_lbl.setAlignment(Qt.AlignCenter)
        self.ivs_hp_lbl.setStyleSheet('font-size: 9px; font-weight: 600; color: #FFFFFF; background: transparent; border: none; padding: 1px 0px;')
        self.ivs_hp_lbl.setCursor(Qt.PointingHandCursor)
        self.ivs_hp_lbl.installEventFilter(self)
        ivs_row.addWidget(self.ivs_hp_lbl)
        self.ivs_atk_lbl = QLabel('100')
        self.ivs_atk_lbl.setFixedWidth(24)
        self.ivs_atk_lbl.setAlignment(Qt.AlignCenter)
        self.ivs_atk_lbl.setStyleSheet('font-size: 9px; font-weight: 600; color: #FFFFFF; background: transparent; border: none; padding: 1px 0px;')
        self.ivs_atk_lbl.setCursor(Qt.PointingHandCursor)
        self.ivs_atk_lbl.installEventFilter(self)
        ivs_row.addWidget(self.ivs_atk_lbl)
        self.ivs_def_lbl = QLabel('100')
        self.ivs_def_lbl.setFixedWidth(24)
        self.ivs_def_lbl.setAlignment(Qt.AlignCenter)
        self.ivs_def_lbl.setStyleSheet('font-size: 9px; font-weight: 600; color: #FFFFFF; background: transparent; border: none; padding: 1px 0px;')
        self.ivs_def_lbl.setCursor(Qt.PointingHandCursor)
        self.ivs_def_lbl.installEventFilter(self)
        ivs_row.addWidget(self.ivs_def_lbl)
        ivs_row.addStretch()
        left_layout.addLayout(ivs_row, 1)
        souls_row = QHBoxLayout()
        souls_row.setSpacing(4)
        self.soul_row_icon = QLabel()
        self.soul_row_icon.setFixedSize(12, 12)
        self.soul_row_icon.setStyleSheet('background: transparent; border: none;')
        srp = _icons._get_ui_icon_pixmap('buildup', 12)
        if srp:
            self.soul_row_icon.setPixmap(srp)
        souls_row.addWidget(self.soul_row_icon)
        self.soul_hp_lbl = QLabel('0')
        self.soul_hp_lbl.setFixedWidth(22)
        self.soul_hp_lbl.setAlignment(Qt.AlignCenter)
        self.soul_hp_lbl.setStyleSheet('font-size: 9px; font-weight: 600; color: #FFFFFF; background: transparent; border: none; padding: 1px 0px;')
        self.soul_hp_lbl.setCursor(Qt.PointingHandCursor)
        self.soul_hp_lbl.installEventFilter(self)
        souls_row.addWidget(self.soul_hp_lbl)
        self.soul_atk_lbl = QLabel('0')
        self.soul_atk_lbl.setFixedWidth(22)
        self.soul_atk_lbl.setAlignment(Qt.AlignCenter)
        self.soul_atk_lbl.setStyleSheet('font-size: 9px; font-weight: 600; color: #FFFFFF; background: transparent; border: none; padding: 1px 0px;')
        self.soul_atk_lbl.setCursor(Qt.PointingHandCursor)
        self.soul_atk_lbl.installEventFilter(self)
        souls_row.addWidget(self.soul_atk_lbl)
        self.soul_def_lbl = QLabel('0')
        self.soul_def_lbl.setFixedWidth(22)
        self.soul_def_lbl.setAlignment(Qt.AlignCenter)
        self.soul_def_lbl.setStyleSheet('font-size: 9px; font-weight: 600; color: #FFFFFF; background: transparent; border: none; padding: 1px 0px;')
        self.soul_def_lbl.setCursor(Qt.PointingHandCursor)
        self.soul_def_lbl.installEventFilter(self)
        souls_row.addWidget(self.soul_def_lbl)
        self.soul_craft_lbl = QLabel('0')
        self.soul_craft_lbl.setFixedWidth(22)
        self.soul_craft_lbl.setAlignment(Qt.AlignCenter)
        self.soul_craft_lbl.setStyleSheet('font-size: 9px; font-weight: 600; color: #FFFFFF; background: transparent; border: none; padding: 1px 0px;')
        self.soul_craft_lbl.setCursor(Qt.PointingHandCursor)
        self.soul_craft_lbl.installEventFilter(self)
        souls_row.addWidget(self.soul_craft_lbl)
        souls_row.addStretch()
        left_layout.addLayout(souls_row, 1)
        columns.addWidget(left_col)
        right_col = QWidget()
        right_col.setStyleSheet('background: transparent; border: none;')
        right_layout = QVBoxLayout(right_col)
        right_layout.setContentsMargins(0, 0, 0, 0)
        right_layout.setSpacing(1)
        trust_row = QHBoxLayout()
        trust_row.setSpacing(0)
        trust_icon = QLabel()
        trust_icon.setFixedSize(14, 14)
        trust_icon.setAlignment(Qt.AlignCenter)
        trust_icon.setAttribute(Qt.WA_TranslucentBackground)
        trust_icon.setStyleSheet('background: transparent; border: none;')
        trust_icon.setCursor(Qt.PointingHandCursor)
        trust_icon.installEventFilter(self)
        self.trust_icon = trust_icon
        trust_pix = _icons._get_ui_icon_pixmap('friendship', 10)
        if trust_pix:
            trust_icon.setPixmap(trust_pix)
        trust_row.addWidget(trust_icon)
        self.trust_bar = QProgressBar()
        self.trust_bar.setFixedHeight(18)
        self.trust_bar.setRange(0, 100)
        self.trust_bar.setValue(0)
        self.trust_bar.setTextVisible(True)
        self.trust_bar.setStyleSheet('QProgressBar { background: rgba(30,20,25,0.6); border: 1px solid rgba(244,114,182,0.20); border-radius: 2px; text-align: center; font-size: 8px; font-weight: 700; color: #FFFFFF; } QProgressBar::chunk { background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #EC4899,stop:1 #F472B6); border-radius: 2px; }')
        trust_row.addWidget(self.trust_bar, 1)
        right_layout.addLayout(trust_row, 1)
        hp_row = QHBoxLayout()
        hp_row.setSpacing(0)
        hp_icon = QLabel('♥')
        hp_icon.setFixedSize(14, 14)
        hp_icon.setAlignment(Qt.AlignCenter)
        hp_icon.setStyleSheet('font-size: 9px; color: #EF4444; background: transparent; border: none;')
        hp_row.addWidget(hp_icon)
        self.hp_bar = QProgressBar()
        self.hp_bar.setFixedHeight(18)
        self.hp_bar.setRange(0, 100)
        self.hp_bar.setValue(100)
        self.hp_bar.setTextVisible(True)
        self.hp_bar.setStyleSheet('QProgressBar { background: rgba(20,40,30,0.6); border: 1px solid rgba(16,185,129,0.2); border-radius: 2px; text-align: center; font-size: 8px; font-weight: 700; color: #FFFFFF; } QProgressBar::chunk { background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #10B981,stop:1 #34D399); border-radius: 2px; }')
        hp_row.addWidget(self.hp_bar, 1)
        right_layout.addLayout(hp_row, 1)
        hunger_row = QHBoxLayout()
        hunger_row.setSpacing(0)
        hunger_icon = QLabel('⚬')
        hunger_icon.setFixedSize(14, 14)
        hunger_icon.setAlignment(Qt.AlignCenter)
        hunger_icon.setStyleSheet('font-size: 9px; color: #F59E0B; background: transparent; border: none;')
        hunger_row.addWidget(hunger_icon)
        self.hunger_bar = QProgressBar()
        self.hunger_bar.setFixedHeight(18)
        self.hunger_bar.setRange(0, 100)
        self.hunger_bar.setValue(53)
        self.hunger_bar.setTextVisible(True)
        self.hunger_bar.setStyleSheet('QProgressBar { background: rgba(40,30,20,0.6); border: 1px solid rgba(245,158,11,0.2); border-radius: 2px; text-align: center; font-size: 8px; font-weight: 700; color: #FFFFFF; } QProgressBar::chunk { background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #F59E0B,stop:1 #FBBF24); border-radius: 2px; }')
        hunger_row.addWidget(self.hunger_bar, 1)
        right_layout.addLayout(hunger_row, 1)
        san_row = QHBoxLayout()
        san_row.setSpacing(0)
        san_icon = QLabel('✦')
        san_icon.setFixedSize(14, 14)
        san_icon.setAlignment(Qt.AlignCenter)
        san_icon.setStyleSheet('font-size: 9px; color: #10B981; background: transparent; border: none;')
        san_row.addWidget(san_icon)
        self.san_bar = QProgressBar()
        self.san_bar.setFixedHeight(18)
        self.san_bar.setRange(0, 100)
        self.san_bar.setValue(100)
        self.san_bar.setTextVisible(True)
        self.san_bar.setStyleSheet('QProgressBar { background: rgba(20,30,40,0.6); border: 1px solid rgba(56,189,248,0.2); border-radius: 2px; text-align: center; font-size: 8px; font-weight: 700; color: #FFFFFF; } QProgressBar::chunk { background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #38BDF8,stop:1 #7DD3FC); border-radius: 2px; }')
        san_row.addWidget(self.san_bar, 1)
        right_layout.addLayout(san_row, 1)
        stats_q = QFrame()
        stats_q.setStyleSheet('background: transparent; border: none;')
        stats_grid = QGridLayout(stats_q)
        stats_grid.setContentsMargins(4, 1, 4, 1)
        stats_grid.setSpacing(2)
        atk_icon = QLabel('⚔')
        atk_icon.setFixedSize(14, 14)
        atk_icon.setAlignment(Qt.AlignCenter)
        atk_icon.setStyleSheet('font-size: 10px; color: #EF4444; background: transparent; border: none;')
        stats_grid.addWidget(atk_icon, 0, 0, Qt.AlignVCenter)
        atk_label = QLabel(t('pal_editor.attack') if t else 'Attack')
        self._atk_label = atk_label
        atk_label.setStyleSheet('font-size: 10px; color: #9CA3AF; background: transparent; border: none;')
        stats_grid.addWidget(atk_label, 0, 1, Qt.AlignVCenter)
        self.atk_lbl = QLabel('0')
        self.atk_lbl.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.atk_lbl.setStyleSheet('font-size: 11px; font-weight: 700; color: #E2E8F0; background: transparent; border: none;')
        stats_grid.addWidget(self.atk_lbl, 0, 2, Qt.AlignVCenter)
        def_icon = QLabel('⚖')
        def_icon.setFixedSize(14, 14)
        def_icon.setAlignment(Qt.AlignCenter)
        def_icon.setStyleSheet('font-size: 10px; color: #3B82F6; background: transparent; border: none;')
        stats_grid.addWidget(def_icon, 1, 0, Qt.AlignVCenter)
        def_label = QLabel(t('pal_editor.defense') if t else 'Defense')
        self._def_label = def_label
        def_label.setStyleSheet('font-size: 10px; color: #9CA3AF; background: transparent; border: none;')
        stats_grid.addWidget(def_label, 1, 1, Qt.AlignVCenter)
        self.def_lbl = QLabel('0')
        self.def_lbl.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.def_lbl.setStyleSheet('font-size: 11px; font-weight: 700; color: #E2E8F0; background: transparent; border: none;')
        stats_grid.addWidget(self.def_lbl, 1, 2, Qt.AlignVCenter)
        wspd_icon = QLabel('⚒')
        wspd_icon.setFixedSize(14, 14)
        wspd_icon.setAlignment(Qt.AlignCenter)
        wspd_icon.setStyleSheet('font-size: 10px; color: #A78BFA; background: transparent; border: none;')
        stats_grid.addWidget(wspd_icon, 2, 0, Qt.AlignVCenter)
        wspd_label = QLabel(t('pal_editor.work_speed') if t else 'Work Speed')
        self._wspd_label = wspd_label
        wspd_label.setStyleSheet('font-size: 10px; color: #9CA3AF; background: transparent; border: none;')
        stats_grid.addWidget(wspd_label, 2, 1, Qt.AlignVCenter)
        self.wspd_lbl = QLabel('0')
        self.wspd_lbl.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.wspd_lbl.setStyleSheet('font-size: 11px; font-weight: 700; color: #E2E8F0; background: transparent; border: none;')
        stats_grid.addWidget(self.wspd_lbl, 2, 2, Qt.AlignVCenter)
        right_layout.addWidget(stats_q)
        columns.addWidget(right_col, 1)
        body_layout.addLayout(columns)
        suit_card = QFrame()
        suit_card.setObjectName('suitFoodCard')
        suit_card.setStyleSheet('QFrame#suitFoodCard { background: rgba(255,255,255,0.02); border: 1px solid rgba(125,211,252,0.1); border-radius: 4px; }')
        card_layout = QVBoxLayout(suit_card)
        card_layout.setContentsMargins(4, 1, 4, 1)
        card_layout.setSpacing(1)
        self.work_icons_container = QWidget()
        self.work_icons_container.setObjectName('wsIcons')
        self.work_icons_container.setStyleSheet('background: transparent; border: none;')
        self.work_icons_layout = QHBoxLayout(self.work_icons_container)
        self.work_icons_layout.setContentsMargins(0, 0, 0, 0)
        self.work_icons_layout.setSpacing(2)
        self.work_icon_labels = []
        self.work_icon_values = []
        for idx, ws_key in enumerate(self.NATIVE_WORK_ORDER):
            wc = QWidget()
            wc.setObjectName('wsWidget')
            wc.setStyleSheet('background: transparent; border: none;')
            wc.setFixedWidth(24)
            vl = QVBoxLayout(wc)
            vl.setContentsMargins(0, 0, 0, 0)
            vl.setSpacing(0)
            ic = QLabel()
            ic.setAlignment(Qt.AlignCenter)
            ic.setFixedSize(22, 22)
            ic.setAttribute(Qt.WA_TranslucentBackground)
            ic.setStyleSheet('background: transparent; border: none;')
            ic.installEventFilter(self)
            palwork_key = self._WORK_SUITABILITY_ICON_KEYS[idx]
            ws_pix = _icons._get_ui_icon_pixmap(palwork_key, 18)
            if ws_pix:
                ic.setPixmap(ws_pix)
                opacity_effect = QGraphicsOpacityEffect()
                opacity_effect.setOpacity(0.06)
                ic.setGraphicsEffect(opacity_effect)
            vl.addWidget(ic, 0, Qt.AlignCenter)
            wl_badge = QFrame()
            wl_badge.setObjectName('wsBadge')
            wl_badge.setStyleSheet('background: transparent; border: none;')
            wl_badge.setFixedHeight(14)
            bd_layout = QVBoxLayout(wl_badge)
            bd_layout.setContentsMargins(2, 0, 2, 0)
            bd_layout.setAlignment(Qt.AlignCenter)
            wl = QLabel('')
            wl.setAlignment(Qt.AlignCenter)
            wl.setStyleSheet('font-size: 9px; font-weight: 700; color: transparent; background: transparent; border: none;')
            wl.setFixedHeight(10)
            wl.installEventFilter(self)
            bd_layout.addWidget(wl)
            vl.addWidget(wl_badge, 0, Qt.AlignCenter)
            self.work_icons_layout.addWidget(wc)
            self.work_icon_labels.append(ic)
            self.work_icon_values.append((wl, ws_key, wl_badge))
        self.work_icons_layout.addStretch()
        card_layout.addWidget(self.work_icons_container)
        food_row = QHBoxLayout()
        food_row.setSpacing(2)
        food_row.addStretch()
        self.food_icon_labels = []
        for i in range(10):
            fc = QLabel()
            fc.setFixedSize(14, 14)
            fc.setAlignment(Qt.AlignCenter)
            fc.setAttribute(Qt.WA_TranslucentBackground)
            fc.setStyleSheet('background: transparent; border: none;')
            food_off_pix = _icons._get_ui_icon_pixmap('food_off', 12)
            if food_off_pix:
                fc.setPixmap(food_off_pix)
                opacity = QGraphicsOpacityEffect()
                opacity.setOpacity(0.14)
                fc.setGraphicsEffect(opacity)
            food_row.addWidget(fc)
            self.food_icon_labels.append(fc)
        card_layout.addLayout(food_row)
        body_layout.addWidget(suit_card)
        parent.addWidget(body, 1)
    def _build_skills(self, parent):
        skill_box = QFrame()
        skill_box.setObjectName('skillBox')
        skill_box.setStyleSheet('QFrame#skillBox { background: rgba(10,16,24,0.95); border: 1.5px solid rgba(125,211,252,0.3); border-radius: 5px; }')
        sb_layout = QVBoxLayout(skill_box)
        sb_layout.setContentsMargins(4, 2, 4, 2)
        sb_layout.setSpacing(3)
        self.partner_frame = QFrame()
        self.partner_frame.setObjectName('partnerBox')
        self.partner_frame.hide()
        self.partner_frame.setStyleSheet('QFrame#partnerBox { background: transparent; border: none; }')
        partner_layout = QVBoxLayout(self.partner_frame)
        partner_layout.setContentsMargins(0, 0, 0, 0)
        partner_layout.setSpacing(1)
        pheader = QHBoxLayout()
        pheader.setSpacing(4)
        self.partner_lvl_lbl = QLabel('Lv 5')
        self.partner_lvl_lbl.setStyleSheet('font-size: 10px; font-weight: 600; color: #F59E0B; background: rgba(245,158,11,0.08); border: 1px solid rgba(245,158,11,0.15); border-radius: 3px; padding: 0 4px;')
        pheader.addWidget(self.partner_lvl_lbl)
        self.partner_name_lbl = QLabel('Aerial Missile')
        self.partner_name_lbl.setStyleSheet('font-size: 11px; font-weight: 700; color: #7DD3FC; background: transparent; border: none;')
        pheader.addWidget(self.partner_name_lbl)
        pheader.addStretch()
        self._c_icon = QPushButton('[C]')
        self._c_icon.setFixedSize(22, 16)
        self._c_icon.setStyleSheet('QPushButton { font-size: 8px; font-weight: 700; color: #7DD3FC; background: rgba(125,211,252,0.08); border: 1px solid rgba(125,211,252,0.2); border-radius: 3px; padding: 0px; margin: 0px; } QPushButton:hover { background: rgba(125,211,252,0.15); }')
        self._c_icon.setCursor(Qt.PointingHandCursor)
        self._c_icon.setToolTip(t('edit_pals.toggle_skills_hint'))
        self._c_icon.clicked.connect(lambda: self.last_clicked_data is not None and self._toggle_skills_view())
        pheader.addWidget(self._c_icon)
        partner_layout.addLayout(pheader)
        self.partner_desc_lbl = QLabel('Fires a barrage of missiles at nearby enemies, dealing massive damage and knocking them back.')
        self.partner_desc_lbl.setWordWrap(True)
        self.partner_desc_lbl.setStyleSheet('font-size: 9px; color: #9CA3AF; background: transparent; border: none; padding: 0 2px;')
        partner_layout.addWidget(self.partner_desc_lbl)
        self.active_skills_frame = QFrame()
        self.active_skills_frame.setObjectName('activeSkillsBox')
        self.active_skills_frame.setStyleSheet('QFrame#activeSkillsBox { background: transparent; border: none; }')
        self.active_skills_frame.installEventFilter(self)
        as_layout = QVBoxLayout(self.active_skills_frame)
        as_layout.setContentsMargins(0, 0, 0, 0)
        as_layout.setSpacing(2)
        as_header = QHBoxLayout()
        as_header.setSpacing(4)
        as_title = QLabel(t('pal_editor.active_skills') if t else 'Active Skills')
        self._as_title = as_title
        as_title.setStyleSheet('font-size: 10px; font-weight: 700; color: #7DD3FC; background: transparent; border: none;')
        as_header.addWidget(as_title)
        self._as_page = 0
        self._as_prev_btn = QPushButton('<')
        self._as_prev_btn.setFixedSize(16, 14)
        self._as_prev_btn.setStyleSheet('QPushButton { font-size: 8px; font-weight: 700; color: #7DD3FC; background: rgba(125,211,252,0.08); border: 1px solid rgba(125,211,252,0.2); border-radius: 3px; padding: 0px; margin: 0px; } QPushButton:hover { background: rgba(125,211,252,0.15); } QPushButton:disabled { color: rgba(255,255,255,0.15); background: transparent; border-color: rgba(255,255,255,0.05); }')
        self._as_prev_btn.setCursor(Qt.PointingHandCursor)
        self._as_prev_btn.clicked.connect(lambda: self._page_as(-1))
        as_header.addWidget(self._as_prev_btn)
        self._as_page_lbl = QLabel('1')
        self._as_page_lbl.setFixedWidth(16)
        self._as_page_lbl.setAlignment(Qt.AlignCenter)
        self._as_page_lbl.setStyleSheet('font-size: 8px; font-weight: 600; color: #94A3B8; background: transparent; border: none;')
        as_header.addWidget(self._as_page_lbl)
        self._as_next_btn = QPushButton('>')
        self._as_next_btn.setFixedSize(16, 14)
        self._as_next_btn.setStyleSheet('QPushButton { font-size: 8px; font-weight: 700; color: #7DD3FC; background: rgba(125,211,252,0.08); border: 1px solid rgba(125,211,252,0.2); border-radius: 3px; padding: 0px; margin: 0px; } QPushButton:hover { background: rgba(125,211,252,0.15); } QPushButton:disabled { color: rgba(255,255,255,0.15); background: transparent; border-color: rgba(255,255,255,0.05); }')
        self._as_next_btn.setCursor(Qt.PointingHandCursor)
        self._as_next_btn.clicked.connect(lambda: self._page_as(1))
        as_header.addWidget(self._as_next_btn)
        as_header.addStretch()
        self._as_c_icon = QPushButton('[C]')
        self._as_c_icon.setFixedSize(22, 14)
        self._as_c_icon.setStyleSheet('QPushButton { font-size: 7px; font-weight: 700; color: #7DD3FC; background: rgba(125,211,252,0.08); border: 1px solid rgba(125,211,252,0.2); border-radius: 3px; padding: 0px; margin: 0px; } QPushButton:hover { background: rgba(125,211,252,0.15); }')
        self._as_c_icon.setCursor(Qt.PointingHandCursor)
        self._as_c_icon.setToolTip(t('edit_pals.toggle_skills_hint'))
        self._as_c_icon.clicked.connect(lambda: self.last_clicked_data is not None and self._toggle_skills_view())
        as_header.addWidget(self._as_c_icon)
        as_layout.addLayout(as_header)
        self.active_skills_list = QVBoxLayout()
        self.active_skills_list.setContentsMargins(0, 0, 0, 0)
        self.active_skills_list.setSpacing(2)
        as_layout.addLayout(self.active_skills_list)
        self.active_skills_frame.setFixedHeight(100)
        sb_layout.addWidget(self.active_skills_frame)
        self.partner_frame.setFixedHeight(100)
        sb_layout.addWidget(self.partner_frame)
        passive_header = QHBoxLayout()
        passive_header.setSpacing(4)
        passive_title = QLabel(t('pal_editor.passive_skills') if t else 'Passive Skills')
        self._passive_title = passive_title
        passive_title.setStyleSheet('font-size: 10px; font-weight: 700; color: #7DD3FC; background: transparent; border: none;')
        passive_header.addWidget(passive_title)
        self._ps_page = 0
        self._ps_prev_btn = QPushButton('<')
        self._ps_prev_btn.setFixedSize(16, 14)
        self._ps_prev_btn.setStyleSheet('QPushButton { font-size: 8px; font-weight: 700; color: #7DD3FC; background: rgba(125,211,252,0.08); border: 1px solid rgba(125,211,252,0.2); border-radius: 3px; padding: 0px; margin: 0px; } QPushButton:hover { background: rgba(125,211,252,0.15); } QPushButton:disabled { color: rgba(255,255,255,0.15); background: transparent; border-color: rgba(255,255,255,0.05); }')
        self._ps_prev_btn.setCursor(Qt.PointingHandCursor)
        self._ps_prev_btn.clicked.connect(lambda: self._page_ps(-1))
        passive_header.addWidget(self._ps_prev_btn)
        self._ps_page_lbl = QLabel('1')
        self._ps_page_lbl.setFixedWidth(16)
        self._ps_page_lbl.setAlignment(Qt.AlignCenter)
        self._ps_page_lbl.setStyleSheet('font-size: 8px; font-weight: 600; color: #94A3B8; background: transparent; border: none;')
        passive_header.addWidget(self._ps_page_lbl)
        self._ps_next_btn = QPushButton('>')
        self._ps_next_btn.setFixedSize(16, 14)
        self._ps_next_btn.setStyleSheet('QPushButton { font-size: 8px; font-weight: 700; color: #7DD3FC; background: rgba(125,211,252,0.08); border: 1px solid rgba(125,211,252,0.2); border-radius: 3px; padding: 0px; margin: 0px; } QPushButton:hover { background: rgba(125,211,252,0.15); } QPushButton:disabled { color: rgba(255,255,255,0.15); background: transparent; border-color: rgba(255,255,255,0.05); }')
        self._ps_next_btn.setCursor(Qt.PointingHandCursor)
        self._ps_next_btn.clicked.connect(lambda: self._page_ps(1))
        passive_header.addWidget(self._ps_next_btn)
        passive_header.addStretch()
        self._l_icon = QPushButton('[L]')
        self._l_icon.setFixedSize(22, 14)
        self._l_icon.setStyleSheet('QPushButton { font-size: 7px; font-weight: 700; color: #7DD3FC; background: rgba(125,211,252,0.08); border: 1px solid rgba(125,211,252,0.2); border-radius: 3px; padding: 0px; margin: 0px; } QPushButton:hover { background: rgba(125,211,252,0.15); }')
        self._l_icon.setCursor(Qt.PointingHandCursor)
        self._l_icon.setToolTip(t('edit_pals.loadouts_hint'))
        self._l_icon.clicked.connect(lambda: self.last_clicked_data is not None and self._on_passive_loadout())
        passive_header.addWidget(self._l_icon)
        sb_layout.addLayout(passive_header)
        pg = QWidget()
        pg.setStyleSheet('background: transparent; border: none;')
        self.passive_container = pg
        pg.installEventFilter(self)
        pg_layout = QGridLayout(pg)
        pg_layout.setContentsMargins(0, 0, 0, 0)
        pg_layout.setSpacing(2)
        _, _, default_tc = PalFrame._RANK_COLORS[1]
        default_bg = PalFrame._RANK_COLORS[1][0]
        placeholder_names = ['Runner', 'Swift', 'Legend', 'Surge of the World Tree']
        self.passive_slots = []
        self.passive_cards = []
        self.passive_rank_icons = []
        for i, pname in enumerate(placeholder_names):
            card = QFrame()
            card.setObjectName('passiveCard')
            card._pal_info = self
            card.setFixedHeight(28)
            card.setStyleSheet(f'QFrame#passiveCard {{ background: {default_bg}; border: none; border-radius: 4px; }}')
            card_layout = QHBoxLayout(card)
            card_layout.setContentsMargins(6, 0, 6, 0)
            card_layout.setSpacing(2)
            card_layout.setAlignment(Qt.AlignVCenter)
            plbl = QLabel(pname)
            plbl.setStyleSheet(f'font-size: 10px; font-weight: 700; color: {default_tc}; background: transparent; border: none;')
            card_layout.addWidget(plbl, 1)
            card_layout.addStretch()
            rank_icon = QLabel()
            rank_icon.setFixedSize(14, 14)
            rank_icon.setAlignment(Qt.AlignCenter)
            rank_icon.setStyleSheet('background: transparent; border: none;')
            rank_icon.hide()
            card_layout.addWidget(rank_icon)
            card.setCursor(Qt.PointingHandCursor)
            card.installEventFilter(self)
            btn = QPushButton('', card)
            btn.setStyleSheet('QPushButton { background: transparent; border: none; }')
            btn.setCursor(Qt.PointingHandCursor)
            btn.setGeometry(0, 0, 100, 100)
            btn.clicked.connect(lambda checked=None, idx=i, c=card: self._on_passive_click(idx + self._ps_page * 4, c.mapToGlobal(QPoint(0, c.height()))))
            row, col = (i // 2, i % 2)
            pg_layout.addWidget(card, row, col)
            self.passive_slots.append(plbl)
            self.passive_cards.append(card)
            self.passive_rank_icons.append(rank_icon)
        self.passive_overlays = []
        for i, card in enumerate(self.passive_cards):
            overlay = PassiveEffectOverlay(card)
            self.passive_overlays.append(overlay)
        sb_layout.addWidget(pg)
        parent.addWidget(skill_box)